# Generated by Django 3.1 on 2023-04-20 18:14

import apps.reservations.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('pax_seats', models.IntegerField()),
                ('first_class_seats', models.IntegerField()),
                ('actived', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('nameCode', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='airline')),
                ('actived', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='BaggagePolicy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('identifier', models.CharField(max_length=100)),
                ('baggagePolicy', models.FileField(blank=True, null=True, upload_to='baggage-policy', validators=[apps.reservations.validators.validate_file_extension])),
                ('actived', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('zelle', models.CharField(blank=True, max_length=100, null=True)),
                ('zelle_owner', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('paid', models.BooleanField(blank=True, default=None, null=True)),
                ('liquidated', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Charter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='charter')),
                ('url', models.URLField(blank=True, null=True)),
                ('actived', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClassType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.IntegerField()),
                ('name_es', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('css', models.TextField(blank=True, null=True)),
                ('actived', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Destinatation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=300)),
                ('country', models.CharField(max_length=300)),
                ('cityCode', models.CharField(max_length=3)),
                ('countryCode', models.CharField(max_length=3)),
                ('begin', models.BooleanField(default=True)),
                ('destination', models.BooleanField(default=True)),
                ('actived', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gate', models.CharField(max_length=20)),
                ('number', models.CharField(max_length=5)),
                ('checkinMoment', models.IntegerField(default=4)),
                ('departure', models.TimeField()),
                ('arrival', models.TimeField()),
                ('date', models.DateField()),
                ('ability', models.IntegerField(default=1)),
                ('priceAdult', models.FloatField()),
                ('revenueAdult', models.FloatField()),
                ('priceChildren', models.FloatField()),
                ('revenueChildren', models.FloatField()),
                ('priceInfant', models.FloatField()),
                ('revenueInfant', models.FloatField()),
                ('actived', models.BooleanField(default=True)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.aircraft')),
                ('baggagePolicy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baggage_policy', to='reservations.baggagepolicy')),
                ('begin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='From', to='reservations.destinatation')),
                ('charter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservations.charter')),
                ('class_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_type', to='reservations.classtype')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='To', to='reservations.destinatation')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('firstName', models.CharField(max_length=100)),
                ('middleName', models.CharField(blank=True, max_length=100, null=True)),
                ('lastName', models.CharField(max_length=100)),
                ('motherLastName', models.CharField(blank=True, max_length=100, null=True)),
                ('birth', models.DateField()),
                ('gender', models.CharField(max_length=1)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('imageDocument', models.ImageField(blank=True, null=True, upload_to='booking-document')),
                ('documentNumber', models.CharField(max_length=14)),
                ('documentExpiration', models.DateField()),
                ('documentType', models.CharField(max_length=50)),
                ('documentCountry', models.CharField(max_length=50)),
                ('imageSecondaryDocument', models.ImageField(blank=True, null=True, upload_to='booking-document')),
                ('secondaryDocumentNumber', models.CharField(blank=True, max_length=14, null=True)),
                ('secondaryDocumentExpiration', models.DateField(blank=True, null=True)),
                ('secondaryDocumentType', models.CharField(blank=True, max_length=50, null=True)),
                ('secondaryDocumentCountry', models.CharField(blank=True, max_length=50, null=True)),
                ('streetBegin', models.CharField(max_length=200)),
                ('cityBegin', models.CharField(max_length=100)),
                ('stateBegin', models.CharField(max_length=100)),
                ('streetTo', models.CharField(max_length=200)),
                ('cityTo', models.CharField(max_length=100)),
                ('stateTo', models.CharField(max_length=100)),
                ('reservationCode', models.BigIntegerField()),
                ('pnr', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.FloatField(default=0)),
                ('revenue', models.FloatField(default=0)),
                ('license', models.CharField(blank=True, max_length=100, null=True)),
                ('actived', models.BooleanField(default=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill', to='reservations.bill')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='reservations.flight')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='aircraft',
            name='carrier_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.airline'),
        ),
    ]
