# Generated by Django 3.1 on 2023-03-05 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_auto_20230304_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='reservationCode',
            field=models.BigIntegerField(),
        ),
    ]
