# Generated by Django 3.1 on 2023-04-22 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_flight_agencycommission'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='liquidated',
            field=models.FloatField(default=0),
        ),
    ]
