# Generated by Django 3.1 on 2023-04-22 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_flight_liquidated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='liquidated',
        ),
        migrations.AddField(
            model_name='booking',
            name='liquidated',
            field=models.FloatField(default=0),
        ),
    ]
