# Generated by Django 3.1 on 2023-06-14 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_auto_20230426_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='packagesOnly',
            field=models.BooleanField(default=False),
        ),
    ]
