# Generated by Django 3.1 on 2023-08-29 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_flight_packagesonly'),
    ]

    operations = [
        migrations.CreateModel(
            name='TvImages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='tv_images')),
            ],
        ),
    ]
