# Generated by Django 3.1 on 2023-06-10 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='bill',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='package',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='location',
        ),
        migrations.RemoveField(
            model_name='vacationpackage',
            name='airline',
        ),
        migrations.RemoveField(
            model_name='vacationpackage',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='vacationpackage',
            name='origen',
        ),
        migrations.RemoveField(
            model_name='vacationpackage',
            name='room_type',
        ),
        migrations.RemoveField(
            model_name='vacationpackage',
            name='transport',
        ),
        migrations.DeleteModel(
            name='Airline',
        ),
        migrations.DeleteModel(
            name='Bill',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Destinatation',
        ),
        migrations.DeleteModel(
            name='Hotel',
        ),
        migrations.DeleteModel(
            name='RoomType',
        ),
        migrations.DeleteModel(
            name='Transport',
        ),
        migrations.DeleteModel(
            name='VacationPackage',
        ),
    ]
