# Generated by Django 3.1 on 2023-06-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_airline_bill_booking_destinatation_hotel_roomtype_transport_vacationpackage'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacationpackage',
            name='arrival_flight_return',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacationpackage',
            name='arrival_traslate_return',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacationpackage',
            name='departure_flight_return',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacationpackage',
            name='departure_traslate_return',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vacationpackage',
            name='arrival_flight',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vacationpackage',
            name='arrival_traslate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vacationpackage',
            name='departure_flight',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vacationpackage',
            name='departure_traslate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
