# Generated by Django 3.1 on 2023-06-17 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0006_auto_20230614_1841'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Airline',
        ),
    ]
