# Generated by Django 3.1 on 2023-06-25 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0007_delete_airline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='maxAdults',
        ),
        migrations.RemoveField(
            model_name='room',
            name='maxChildrens',
        ),
        migrations.RemoveField(
            model_name='room',
            name='maxInfants',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_space',
        ),
        migrations.RemoveField(
            model_name='vacationpackage',
            name='accommodation',
        ),
        migrations.RemoveField(
            model_name='vacationpackage',
            name='servicesInclude',
        ),
    ]
