# Generated by Django 3.1 on 2023-07-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0010_auto_20230702_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=100)),
                ('middleName', models.CharField(blank=True, max_length=100, null=True)),
                ('lastName', models.CharField(max_length=100)),
                ('motherLastName', models.CharField(blank=True, max_length=100, null=True)),
                ('birth', models.DateField()),
                ('gender', models.CharField(max_length=1)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('imageDocument', models.ImageField(blank=True, null=True, upload_to='package-booking-document')),
                ('documentNumber', models.CharField(max_length=14)),
                ('documentExpiration', models.DateField()),
                ('documentType', models.CharField(max_length=50)),
                ('documentCountry', models.CharField(max_length=50)),
                ('imageSecondaryDocument', models.ImageField(blank=True, null=True, upload_to='package-booking-document')),
                ('secondaryDocumentNumber', models.CharField(blank=True, max_length=14, null=True)),
                ('secondaryDocumentExpiration', models.DateField(blank=True, null=True)),
                ('secondaryDocumentType', models.CharField(blank=True, max_length=50, null=True)),
                ('secondaryDocumentCountry', models.CharField(blank=True, max_length=50, null=True)),
                ('streetBegin', models.CharField(max_length=200)),
                ('cityBegin', models.CharField(max_length=100)),
                ('stateBegin', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='booking',
            name='birth',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='cityBegin',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='documentCountry',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='documentExpiration',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='documentNumber',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='documentType',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='email',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='imageDocument',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='imageSecondaryDocument',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='license',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='middleName',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='motherLastName',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='secondaryDocumentCountry',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='secondaryDocumentExpiration',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='secondaryDocumentNumber',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='secondaryDocumentType',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='stateBegin',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='streetBegin',
        ),
        migrations.AddField(
            model_name='booking',
            name='clients',
            field=models.ManyToManyField(to='hotels.Client'),
        ),
    ]
