# Generated by Django 3.1 on 2023-04-26 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20230422_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencie',
            name='credit',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='is_admin_agencie',
            field=models.BooleanField(default=False),
        ),
    ]
