# Generated by Django 3.1 on 2023-04-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20230426_0802'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditRecharge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('zelle', models.CharField(blank=True, max_length=100, null=True)),
                ('zelle_owner', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.FloatField(default=0)),
                ('confirm', models.BooleanField(blank=True, default=None, null=True)),
            ],
        ),
    ]
