# Generated by Django 3.1 on 2023-04-30 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_creditrecharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditrecharge',
            name='agencie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agencie_credit_recharge', to='user.agencie'),
        ),
        migrations.AddField(
            model_name='creditrecharge',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_account_credit_recharge', to=settings.AUTH_USER_MODEL),
        ),
    ]
