# Generated by Django 3.1 on 2023-04-30 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20230430_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditrecharge',
            name='amount_confirmed',
            field=models.FloatField(default=0),
        ),
    ]
