# Generated by Django 3.1 on 2023-07-31 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_creditrecharge_amount_confirmed'),
    ]

    operations = [
        migrations.CreateModel(
            name='agency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=255)),
                ('email2', models.EmailField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('phone2', models.CharField(blank=True, max_length=20, null=True)),
                ('phone3', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='agency')),
                ('revenue', models.FloatField(default=10.0)),
                ('license', models.FileField(blank=True, null=True, upload_to='agency-license')),
                ('credit', models.FloatField(default=0)),
                ('actived', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameField(
            model_name='useraccount',
            old_name='is_admin_agencie',
            new_name='is_admin_agency',
        ),
        migrations.RemoveField(
            model_name='creditrecharge',
            name='agencie',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='agencie',
        ),
        migrations.DeleteModel(
            name='Agencie',
        ),
        migrations.AddField(
            model_name='creditrecharge',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_credit_recharge', to='user.agency'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency', to='user.agency'),
        ),
    ]
