# Generated by Django 3.1 on 2023-08-02 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20230731_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='email2',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='phone2',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='phone3',
        ),
        migrations.AddField(
            model_name='agency',
            name='contact_email',
            field=models.EmailField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agency',
            name='contact_name',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agency',
            name='contact_phone',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agency',
            name='fax',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agency',
            name='fei_ein_number',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agency',
            name='seller_travel_number',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
