
en = {
    # -- INDEX --
    "index_t1":"Flights to multiple destination with",
    "index_t2":"Regular Airlines And Charters",
    "index_t3":"WHERE DO YOU WANT TO GO?",
    "rt":"ROUND-TRIP",
    "ow":"ONE-WAY",
    "search_now":"SEARCH NOW",
    "from":"From",
    "to":"To",
    "trip":"Trip",
    "departure":"Departure",
    "return":"Return",
    "passengers":"Passengers",
    "adults":"Adults",
    "adults_ages":"Ages 18 and over",
    "children":"Children",
    "children_ages":"Ages 2 - 11",
    "infants":"Infants",
    "infants_ages":"Younger than 2",
    "ready":"Ready",
    "index_t4":"Select the day of departure",
    "index_t5":"Select the day of return",

    
    "index_vacations":"Book now the vacation you deserve!",
    
    "index_t6":"Upscale, all-inclusive luxury resorts for the whole family in tropical destinations like Cancun, Punta Cana, Jamaica", # Royalton Luxury Resorts           ADD_CUBA, and Cuba.
    "index_t7":"Indulge in adults-only all-inclusive luxury. Party your way on our private beach and exclusive poolside Rooftop Lounge.", # Royalton Chic Cancún
    "index_t8":"Take a dip with the whole family at an all-inclusive resort featuring an exciting water park, a variety of restaurants, and more.", # Royalton Splash Rivera
    "index_t9":"Family-friendly, all-inclusive luxury resort and casino offers delicious cuisine, pristine beaches, water sports and kids' clubs.", # Royalton Barvaro Resorts
    
    "index_hotel1":"Royalton Luxury Resorts",
    "index_hotel2":"Royalton Chic Cancún",
    "index_hotel3":"Royalton Splash Rivera",
    "index_hotel4":"Royalton Barvaro Resorts",
    
    # -- RESEÑAS --
    "index_resena":"What do customers think about us?",
    "index_resena_t1":"Jeard C Escobar",
    "index_resena_t2":"Excellent...thank you for everything. Helpful and professional",
    "index_resena_t3":"EDEL S",
    "index_resena_t4":"I went to extend my passport for two more years and excellent service and attention, they are very aware of what is happening in terms of emigration and others.", # ADD_CUBA- I went to extend my Cuban passport for two more years and excellent service and attention, they are very aware of what is happening in terms of emigration and others.
    "index_resena_t5":"Rafael Arango",
    "index_resena_t6":"The vacation packages that they promote are the most TOP, I love the offers they have from CANCUN",
    "index_resena_t7":"See more Reviews",

    # -- FOOTER --
    "footer_t1":"We are a Family Travel agency with more than 20 years of experience, our fundamental objective is to satisfy our clients and that they know that they count on us for their Travel and immigration procedures.",
    "footer_t2":"SERVICES",
    "footer_t3":"Consular Procedures",
    "footer_t4":"Immigration procedures",
    "footer_t5":"Vacations to the caribbean",
    "footer_t6":"Europe and the World",
    "footer_t7":"Stay informed of our promotions",
    "footer_t8":"Subscribe to the Newsletter",
    "footer_t9":"Subscribe",
    "footer_t10":"© Copyright 2023 TramiTravel. All rights reserved.",

    # -- LOGIN --
    "login_t1":"Login in to our platform",
    "login_t2":"Your email",
    "login_t3":"Your password",
    "login_t4":"Lost Password?",
    "login_t5":"Login to your account",
    "login_t6":"Not registered?",
    "login_t6":"Not registered?",
    "login_t7":"Create account",
    "login_t8":"Sign in to our platform",
    "login_t9":"Confirm your password",
    "login_t10":"Do you already have an account?",
    "login_t11":"Login account",
    "login_t12":"A confirmation code has been sent to your email, put the code in the following box",
    "login_t13":"Confirm Code",
    "login_t14":"The confirm code is incorrect",
    "login_t15":"Verify confirmation code",
    "login_t16":"The username or password is incorrect",
    "login_continue":"Login To Continue",

    "reset_passwor_1":"Do not you remember your password?",
    "reset_passwor_2":"Restore password",
    "reset_passwor_3":"New Password",

    # -- MENU --
    "menu_t1":"Flights",
    "menu_t2":"Contact",
    "menu_t3":"Pro User",
    "trips":"Trips",
    "signout":"Sign out",
    "account":"Account",
    "started":"Get started",
    "login":"Log in",
    
    # -- Flight --
    "duration":"Duration",
    "outbound_flight":"Outbound flight",
    "return_flight":"Return flight",
    "no_flight":"There are no flights available for this date",
    "available_flight":"The closest dates with available flights are:",
    "continue":"Continue",
    "economic":"Economic",
    "class":"Class",

    # -- BOOKING --
    "booking_t1":"Your trip total",
    "booking_t2":"If at the date of the flight, the child are over two years old, then the total amount will be affected",
    "attention":"Attention",
    "personalInformation":"Personal Information",
    "adult_passenger":"Adult passenger",
    "children_passenger":"Children  passenger",
    "infant_passenger":"Infant passenger",
    "first_name":"First Name",
    "middle_name":"Middle Name",
    "last_name":"Last Name",
    "mother_name":"Mother's Name",
    "date_birth":"Date of birth",
    "select_date_birth":"Select the date of birth",
    "gender":"Gender",
    "male":"Male",
    "female":"Female",
    "primary_document_information":"Primary document information",
    "secondary_document_information":"Secondary document information",
    "booking_t3":"WARNING: If you have Cuban residence, it is mandatory that you provide the information of the Cuban document.",
    "not_available":"Not available",
    "document_number":"Document Number",
    "expiration_date":"Expiration Date",
    "document_type":"Document Type",
    "country_document":"Country of Document",
    "passport":"Passport",
    "country_document_s2":"U.S. Permanent Resident Card",
    "country_document_s3":"U.S. Refugee Permit Travel Document",
    "country_document_s4":"U.S. Re-entry Permit Travel Document",
    "address_es":"",
    "address_en":"Address",
    "street":"Street",
    "city":"City",
    "state":"State",
    "zip_code":"Zip Code",
    "trip_contact":"Trip contact",
    "email":"Email",
    "confirm_email":"Confirm Email",
    "phone_number":"Phone Number",
    
    # -- CONTACT --
    "contact_t1":"For more information or to make an appointment with our agency contact us",
    "mensaje":"Message",
    "contact_mensaje_placeholder":"Write here the message you want to send to support...",
    "full_name":"Name and surname",
    "fax":"Fax",
    "contact_t2":"Work schedules",
    "contact_t3":"Monday- Friday 9AM–6PM / Saturdays: 9AM–3PM",
    "send":"Send",
    
    "description":"Description",
    
    # -- ticket --
    "ticket_t1":"Pay with",
    "ticket_t2":"Payment to be confirmed",
    "ticket_t3":"Your payment has not been registered, if you have made the payment, register the payment again, if I don't make the payment via Zelle, you must make the payment.",
    "ticket_t4":"Remaining time to pay",
    "ticket_t4":"Make payment",
    "ticket_t5":"Put TramiTravel data",
    "ticket_t6":"Scan the QR code or make the transfer to the following account:",
    "ticket_t7":"Add the amount to transfer",
    "ticket_t8":"In the transfer box, place the following amount:",
    "ticket_t9":"Add confirmation code",
    "ticket_t10":"For greater security, in the message box put the following code:",
    "ticket_t11":"Enter the details of the account from which you made the transfer",
    "ticket_t12":"Email of Zelle",
    "ticket_t13":"Phone of Zelle",
    "ticket_t14":"Register Payment",
    "ticket_t15":"There are no registered reservations",
    "ticket_t16":"Your Zelle details are required",

    "step":"Step",
    "hours":"Hours",
    "minutes":"Minutes",
    "seconds":"Seconds",
    "bookings":"BOOKINGS",
    "pending_bookings":"PENDING BOOKINGS",
    "select_bookings":"Select a booking",
    "t1_delete_bookings":"Delete booking",
    "t2_delete_bookings":"Are you sure to delete the booking?",
    "or":"or",
    
    # -- Message --
    "succesMessage":"Our staff will contact you in a moment. Thank you for contacting us.",
    "delete":"Delete",
    "cancel":"Cancel",
}

sp = {
    # -- INDEX --
    "index_t1":"Viajes a multiples destinos con",
    "index_t2":"Aerolíneas Regulares Charters",
    "index_t3":"¿A DONDE QUIERES IR?",
    "rt":"IDA Y VUELTA",
    "ow":"SOLO IDA",
    "search_now":"BUSCAR AHORA",
    "from":"De",
    "to":"A",
    "trip":"Viaje",
    "departure":"Partida",
    "return":"Retorno",
    "passengers":"Pasajeros",
    "adults":"Adultos",
    "adults_ages":"Mayores de 18 años",
    "children":"Niños",
    "children_ages":"Edades 2 - 11",
    "infants":"Infantes",
    "infants_ages":"Menor de 2 años",
    "ready":"Listo",
    "index_t4":"Seleccione el día de salida",
    "index_t5":"Seleccione el día de retorno",

    
    "index_vacations":"¡Reserva ahora las vacaciones que te mereces!",
    
    "index_t6":"Resorts de lujo exclusivos con todo incluido para toda la familia en destinos tropicales como Cancún, Punta Cana, Jamaica.", # Royalton Luxury Resorts  ADD_CUBA- Resorts de lujo exclusivos con todo incluido para toda la familia en destinos tropicales como Cancún, Punta Cana, Jamaica y Cuba.
    "index_t7":"Disfrute del lujo todo incluido solo para adultos. Diviértase a su manera en nuestra playa privada y en el exclusivo Rooftop Lounge junto a la piscina.", # Royalton Chic Cancún
    "index_t8":"Date un chapuzón con toda la familia en un resort todo incluido que cuenta con un emocionante parque acuático, una variedad de restaurantes y más.", # Royalton Splash Rivera
    "index_t9":"Resort y casino de lujo con todo incluido, ideal para familias, que ofrece deliciosa cocina, playas vírgenes, deportes acuáticos y clubes infantiles.", # Royalton Barvaro Resorts
    
    "index_hotel1":"Royalton Luxury Resorts",
    "index_hotel2":"Royalton Chic Cancún",
    "index_hotel3":"Royalton Splash Rivera",
    "index_hotel4":"Royalton Barvaro Resorts",
    
    # -- RESEÑAS --
    "index_resena":"¿Qué opinan los clientes de nosotros?",
    "index_resena_t1":"Jeard C Escobar",
    "index_resena_t2":"Excelente... gracias por todo. Útil y profesional",
    "index_resena_t3":"EDEL S",
    "index_resena_t4":"Fui a prorrogar mi pasaporte cubano por dos años más y excelente servicio y atención, están muy pendientes de lo que está pasando en cuanto a emigración y demás.",
    "index_resena_t5":"Rafael Arango",
    "index_resena_t6":"Los paquetes vacacionales que promocionan son lo mas TOP, me encantan las ofertas que tienen de CANCUN",
    "index_resena_t7":"Ver más reseñas",

    # -- FOOTER --
    "footer_t1":"Somos una agencia de Viajes Familiares con más de 20 años de experiencia, nuestro objetivo fundamental es satisfacer a nuestros clientes y que sepan que cuentan con nosotros para sus Viajes y trámites migratorios.",
    "footer_t2":"SERVICIOS",
    "footer_t3":"Trámites Consulares",
    "footer_t4":"Trámites migratorios",
    "footer_t5":"vacaciones al caribe",
    "footer_t6":"Europa y el mundo",
    "footer_t7":"Mantente informado de nuestras promociones.",
    "footer_t8":"Suscríbete al boletín",
    "footer_t9":"Suscríbete",
    "footer_t10":"© Copyright 2023 TramiTravel. Todos los derechos reservados.",

    # -- LOGIN --
    "login_t1":"Inicie sesión en nuestra plataforma",
    "login_t2":"Tu correo electrónico",
    "login_t3":"Tu contraseña",
    "login_t4":"¿Perdiste la contraseña?",
    "login_t5":"Ingrese a su cuenta",
    "login_t6":"¿No registrado?",
    "login_t7":"Crear una cuenta",
    "login_t8":"Regístrate en nuestra plataforma",
    "login_t9":"Confirmar la contraseña",
    "login_t10":"¿Ya tienes una cuenta?",
    "login_t11":"Iniciar sesión",
    "login_t12":"Se ha enviado un código de confirmación a su correo electrónico, coloque el código en el siguiente cuadro",
    "login_t13":"Código de confirmación",
    "login_t14":"El código de confirmación es incorrecto.",
    "login_t15":"Verificar código de confirmación",
    "login_t16":"El nombre de usuario o contraseña son incorrectos",
    "login_continue":"Iniciar sesión para continuar",
    
    "reset_passwor_1":"No recuerdas tu contraseña?",
    "reset_passwor_2":"Restablecer contraseña",
    "reset_passwor_3":"Nueva contraseña",

    # -- MENU --
    "menu_t1":"Vuelos",
    "menu_t2":"Contáctanos",
    "menu_t3":"Usuario",
    "trips":"Voletos",
    "signout":"Cerrar sesión",
    "account":"Cuenta",
    "started":"Empezar",
    "login":"Entrar",
    
    # -- Flight --
    "duration":"Duración",
    "outbound_flight":"Vuelo de ida",
    "return_flight":"Vuelo de regreso",
    "no_flight":"No hay vuelos disponibles para esta fecha",
    "available_flight":"Las fechas más cercanas con vuelos disponibles son:",
    "continue":"Continuar",
    "economic":"Clase",
    "class":"Económica",

    # -- BOOKING --
    "booking_t1":"Total de tu viaje",
    "booking_t2":"Si a la fecha del vuelo, el niño tiene más de dos años, entonces el monto total se verá afectado.",
    "attention":"Atención",
    "personalInformation":"Informacion personal",
    "adult_passenger":"Pasajero adulto - ",
    "children_passenger":"Pasajero niño - ",
    "infant_passenger":"Pasajero infantil - ",
    "first_name":"Nombre",
    "middle_name":"Segundo nombre",
    "last_name":"Apellido",
    "mother_name":"Segundo apellido",
    "date_birth":"Fecha de nacimiento",
    "select_date_birth":"Seleccione la fecha de nacimiento",
    "gender":"Género",
    "male":"Masculino",
    "female":"Femenino",
    "primary_document_information":"Información del documento principal",
    "secondary_document_information":"Información del documento secundario",
    "booking_t3":"ADVERTENCIA: Si tiene residencia cubana, es obligatorio que proporcione la información del documento cubano.",
    "not_available":"No disponible",
    "document_number":"Número del Documento",
    "expiration_date":"Fecha de caducidad",
    "document_type":"Tipo de Documento",
    "country_document":"País del documento",
    "passport":"Pasaporte",
    "country_document_s2":"Tarjeta de residente permanente de U.S.",
    "country_document_s3":"Permiso de Refugiado Documento de Viaje de U.S.",
    "country_document_s4":"Permiso de reingreso Documento de viaje de U.S.",
    "address_es":"Dirección en",
    "address_en":"",
    "street":"Calle",
    "city":"Ciudad",
    "state":"Estado",
    "zip_code":"Código postal",
    "trip_contact":"Contacto",
    "email":"Correo electrónico",
    "confirm_email":"Confirmar correo electrónico",
    "phone_number":"Número de teléfono",
    
    # -- CONTACT --
    "contact_t1":"Para más información o concertar una cita con nuestra agencia contáctenos",
    "mensaje":"Mensaje",
    "contact_mensaje_placeholder":"Esriba acá el mensaje que desea enviar a soporte...",
    "full_name":"Nombre y apellidos",
    "fax":"Fax",
    "contact_t2":"Horarios de trabajo",
    "contact_t3":"Lunes- Viernes 9AM–6PM / Sábados: 9AM–3PM",
    "send":"Enviar",
    
    "description":"Descripción",
    
    # -- ticket --
    "ticket_t1":"Pagar con",
    "ticket_t2":"Pago por confirmar",
    "ticket_t3":"Tu pago no ha sido registrado, si has realizado el pago, registra el pago nuevamente, si no realizo el pago vía Zelle, debes realizar el pago.",
    "ticket_t4":"Tiempo restante para pagar",
    "ticket_t4":"Hacer el pago",
    "ticket_t5":"Poner datos de TramiTravel",
    "ticket_t6":"Escanea el código QR o realiza la transferencia a la siguiente cuenta:",
    "ticket_t7":"Agrega el monto a transferir",
    "ticket_t8":"En la caja de transferencia, coloque la siguiente cantidad:",
    "ticket_t9":"Añadir código de confirmación",
    "ticket_t10":"Para mayor seguridad, en el cuadro de mensaje ponga el siguiente código:",
    "ticket_t11":"Introduce los datos de la cuenta desde la que realizaste la transferencia",
    "ticket_t12":"Correo electrónico de Zelle",
    "ticket_t13":"Número de teléfono de Zelle",
    "ticket_t14":"Registrar Pago",
    "ticket_t15":"No hay reservas registradas",
    "ticket_t16":"Sus datos de Zelle son obligatorios",

    "step":"Paso",
    "hours":"Horas",
    "minutes":"Minutos",
    "seconds":"Segundos",
    "bookings":"RESERVAS",
    "pending_bookings":"RESERVAS PENDIENTES",
    "select_bookings":"Seleccione una reserva",
    "t1_delete_bookings":"Eliminar reserva",
    "t2_delete_bookings":"¿Se encuentra seguro de eliminar la reserva?",
    "or":"or",
    
    # -- succesMessage --
    "succesMessage":"Nuestro personal se comunicará con usted en un momento. Gracias por contactarnos.",
    "delete":"Eliminar",
    "cancel":"Cancelar",
}


def get_strings(cookies):
    try :
        lang = cookies["language"]
        print(lang)
        if lang == "en":return en,lang
        else:return sp,lang
    except:
        return en,"en"