# Generated by Django 3.1 on 2023-03-04 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('clave', models.CharField(max_length=300, unique=True)),
                ('valor', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Refill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(max_length=10)),
                ('emailZelle', models.CharField(blank=True, max_length=100, null=True)),
                ('userZelle', models.CharField(blank=True, max_length=100, null=True)),
                ('deposit', models.FloatField()),
                ('receiver', models.FloatField()),
                ('card', models.IntegerField()),
                ('receivingPerson', models.CharField(max_length=150)),
                ('status', models.BooleanField(blank=True, default=None, null=True)),
            ],
        ),
    ]
