# Generated by Django 3.1 on 2023-04-17 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('clave', models.CharField(max_length=300, unique=True)),
                ('valor', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Refill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(max_length=10)),
                ('emailZelle', models.CharField(blank=True, max_length=100, null=True)),
                ('userZelle', models.CharField(blank=True, max_length=100, null=True)),
                ('deposit', models.FloatField()),
                ('receiver', models.FloatField()),
                ('card', models.IntegerField()),
                ('receivingPerson', models.CharField(max_length=150)),
                ('status', models.BooleanField(blank=True, default=None, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
