# Generated by Django 3.1 on 2023-07-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pasms',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('case', models.CharField(max_length=10)),
                ('success', models.BooleanField(default=False)),
            ],
        ),
    ]
