# Generated by Django 3.1 on 2023-07-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pasms',
            name='success',
        ),
        migrations.AddField(
            model_name='pasms',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
