# Generated by Django 3.1 on 2023-07-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20230723_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasms',
            name='case',
            field=models.CharField(max_length=15),
        ),
    ]
