# Generated by Django 3.1 on 2023-07-25 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_auto_20230725_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasms',
            name='case',
            field=models.CharField(max_length=15),
        ),
    ]
