# Generated by Django 3.1 on 2023-11-18 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_auto_20230725_0025'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pasms',
        ),
    ]
