# Generated by Django 3.1 on 2023-03-05 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofert',
            name='description_en',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ofert',
            name='message_es',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
