# Generated by Django 3.1 on 2023-08-22 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_auto_20230810_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofert',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ofert',
            name='description_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ofert',
            name='name_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ofert',
            name='name_es',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
